// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mock

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	protobuf "github.com/larien/product/protos"
)

// New creates a new instance of Server mock
func New() *Mock {
	return &Mock{}
}

// Mock is an autogenerated mock type for the Server type
type Mock struct {
	mock.Mock
}

// Discount provides a mock function with given fields: ctx, in, opts
func (_m *Mock) Discount(ctx context.Context, in *protobuf.DiscountRequest, opts ...grpc.CallOption) (*protobuf.DiscountResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *protobuf.DiscountResponse
	if rf, ok := ret.Get(0).(func(context.Context, *protobuf.DiscountRequest, ...grpc.CallOption) *protobuf.DiscountResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protobuf.DiscountResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *protobuf.DiscountRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
